import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SwitchLang from '../components/SwitchLang'
import { Locale, getDictionary } from './dictionaries'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  params: {
    lang: Locale
  }
}


export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  


  return (
    <html lang="">
      <body className={inter.className}>
        <SwitchLang/>
        {children}
      </body>
    </html>
  )
}
